# if try block are successfully run then else block are executed

try :
    a = int(input("Enter a number : "))

except Exception as e :
    print(e)

else :
    print("Thanku for entering correct number !")

